name: Build source code

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
      with:
        dotnet-version: 10.0.x
    - name: Install dependencies
      run: dotnet restore src/AddressBook.slnx --locked-mode
    - name: Build (Release)
      run: dotnet build src/AddressBook.slnx --configuration Release --no-restore
