name: Build source code

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore src/AddressBook.sln
    - name: Build (Release)
      run: dotnet build src/AddressBook.sln --configuration Release --no-restore